
project_id = "dqtpjqmaoagdwxcjcsap"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322

[studio]
enabled = true
port = 54323
api_url = "http://localhost"

[inbucket]
enabled = true
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
enabled = true
port = 54325
image_transformation = true

[auth]
enabled = true
port = 54327
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://laelvistech.netlify.app"]
jwt_expiry = 3600
refresh_token_rotation_enabled = true
security_update_password_require_reauthentication = true

[edge_runtime]
enabled = true
port = 54328

[[edge_runtime.env_vars]]
name = "SUPABASE_URL"
value = "http://localhost:54321"

[[edge_runtime.env_vars]]
name = "SUPABASE_ANON_KEY"
value = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRxdHBqcW1hb2FnZHd4Y2pjc2FwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MTk4NzcsImV4cCI6MjA2NTQ5NTg3N30.MRnTLA1UKYVSR3fk511xca5YOPxcO1qWh2nyjNbPkG4"

[[edge_runtime.env_vars]]
name = "SUPABASE_SERVICE_ROLE_KEY"
value = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRxdHBqcW1hb2FnZHd4Y2pjc2FwIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc0OTkxOTg3NywiZXhwIjoyMDY1NDk1ODc3fQ.rBBNYXv4FYVQkhrhGOGMaL1lJL6g-vLdJp_VFnz09Ks"

[functions.send-alert-email]
verify_jwt = false

[functions.send-otp-email]
verify_jwt = false

[functions.send-invite-email]
verify_jwt = false
